package com.siemens.cz.junittest.lib;

import static org.junit.Assert.assertTrue;

import org.junit.Test;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'z003dv0s' at '12/3/16 2:00 PM' with Gradle 3.0
 *
 * @author z003dv0s, @date 12/3/16 2:00 PM
 */
public class LibraryTest {

	@Test
	public void testSomeLibraryMethod() {
		// mock();
		Library classUnderTest = new Library();
		assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
	}

}
