package com.siemens.cz.junittest.lib;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'z003dv0s' at '12/3/16 2:00 PM' with Gradle 3.0
 *
 * @author z003dv0s, @date 12/3/16 2:00 PM
 */
public class Library {

	public boolean someLibraryMethod() {
		return true;
	}

}
